import { useEffect, useState } from "react";
import { CheckCircle, Save, User } from "lucide-react";
import { useAuth } from "../context/AuthContext";
import { supabase } from "../lib/supabase";

export default function ProfilePage() {
  const { profile, user, refreshProfile } = useAuth();
  const [firstName, setFirstName] = useState(""); const [lastName, setLastName] = useState("");
  const [saved, setSaved] = useState(false); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { setFirstName(profile?.first_name ?? ""); setLastName(profile?.last_name ?? ""); }, [profile?.first_name, profile?.last_name]);
  const name = [firstName, lastName].filter(Boolean).join(" ") || user?.email || "Customer";
  const initials = name.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase();
  const handleSubmit = async (event: React.FormEvent) => { event.preventDefault(); if (!supabase) return; setSaving(true); setSaved(false); setError(""); const { error: updateError } = await supabase.rpc("update_my_profile", { first_name_input: firstName, last_name_input: lastName }); setSaving(false); if (updateError) return setError(updateError.message); await refreshProfile(); setSaved(true); };
  return <div className="fade-in space-y-8">
    <div className="rounded-2xl border border-line bg-ivory p-6 sm:p-8"><div className="flex items-center gap-5"><div className="flex h-20 w-20 items-center justify-center rounded-full border-2 border-champagne bg-cream"><span className="font-display text-2xl text-gold">{initials}</span></div><div><p className="font-display text-lg text-ink">{name}</p><p className="mt-0.5 text-sm text-espresso-light">{profile?.email || user?.email}</p><p className="mt-3 text-xs text-espresso-light">Customer account</p></div></div></div>
    <form onSubmit={handleSubmit} className="rounded-2xl border border-line bg-ivory p-6 sm:p-8"><div className="mb-6 flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-cream"><User size={16} className="text-gold" /></div><h2 className="font-display text-xl text-ink">Personal Information</h2></div><div className="grid gap-5 sm:grid-cols-2"><label className="flex flex-col gap-1.5"><span className="eyebrow text-espresso-light">First name</span><input required value={firstName} onChange={(e) => { setFirstName(e.target.value); setSaved(false); }} className="rounded-lg border border-line bg-cream/40 px-4 py-3 text-sm text-ink outline-none focus:border-champagne" /></label><label className="flex flex-col gap-1.5"><span className="eyebrow text-espresso-light">Last name</span><input required value={lastName} onChange={(e) => { setLastName(e.target.value); setSaved(false); }} className="rounded-lg border border-line bg-cream/40 px-4 py-3 text-sm text-ink outline-none focus:border-champagne" /></label><label className="flex flex-col gap-1.5 sm:col-span-2"><span className="eyebrow text-espresso-light">Email address</span><input value={profile?.email || user?.email || ""} readOnly className="rounded-lg border border-line bg-cream/40 px-4 py-3 text-sm text-espresso-light outline-none" /><span className="text-xs text-espresso-light">Email changes are managed through your sign-in provider.</span></label></div><div className="mt-8 flex items-center gap-4"><button disabled={saving} type="submit" className="inline-flex items-center gap-2 rounded-full bg-ink px-6 py-3 text-sm font-semibold text-ivory transition-all hover:bg-espresso disabled:opacity-60"><Save size={15} />{saving ? "Saving…" : "Save changes"}</button>{saved && <span className="flex items-center gap-1.5 text-sm text-emerald-700"><CheckCircle size={15} />Saved successfully</span>}</div>{error && <p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}</form>
  </div>;
}
